name: Vue.js CI/CD

on:
  push:
    branches: [ master, develop, test, staging ]
  pull_request:
    branches: [ master, develop, test, staging ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install --no-audit --prefer-offline --legacy-peer-deps
        npm install -D jest @vue/test-utils @vue/vue2-jest babel-jest jest-environment-jsdom jest-transform-stub jest-watch-typeahead
    
    - name: Lint
      run: npm run lint
      
    - name: Run tests
      run: npm test

    # Development Environment
    - name: Build Development
      if: github.ref == 'refs/heads/develop'
      run: npm run build
      env:
        NODE_ENV: development
    
    - name: Deploy to Dev
      if: github.ref == 'refs/heads/develop'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: dev
        
    # Test Environment
    - name: Build Test
      if: github.ref == 'refs/heads/test'
      run: npm run build:test
      env:
        NODE_ENV: test
    
    - name: Deploy to Test
      if: github.ref == 'refs/heads/test'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: test
        
    # Staging Environment
    - name: Build Staging
      if: github.ref == 'refs/heads/staging'
      run: npm run build:staging
      env:
        NODE_ENV: staging
    
    - name: Deploy to Staging
      if: github.ref == 'refs/heads/staging'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: staging
        
    # Production Environment
    - name: Build Production
      if: github.ref == 'refs/heads/master'
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: prod