name: Vue.js CI/CD

on:
  push:
    branches: [ master ]  # 改为 master
  pull_request:
    branches: [ master ]  # 改为 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: |
        pnpm config set registry https://registry.npmmirror.com
        pnpm install
      
    - name: Build
      run: pnpm run build
      
    - name: Upload build files
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
        retention-days: 5