name: Vue.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 更新到 v4 版本
    
    - name: Setup Node.js
      uses: actions/setup-node@v4  # 更新到 v4 版本
      with:
        node-version: '16'
        cache: 'npm'  # 添加缓存提升性能
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Upload build files
      uses: actions/upload-artifact@v4  # 更新到 v4 版本
      with:
        name: dist
        path: dist
        retention-days: 5  # 设置保留时间